### ISSUE TITLE
Call contract._constructor() fails after burrow.contracts.deploy()

### ISSUE THREAD

**Issue by miguelmartinezinf** [monax/bosmarmot#175]
- [ ] `burrow version` 0.22
- [ ] `burrow.js version` 0.20.8
- [ ] `OS` ubuntu 16.04

## Expected Behavior
After deploying a first contract using the call `burrow.contracts.deploy()`, the call `contract._constructor()` should return the address of a new deployed smart contract on Burrow server.

## Actual Behavior 
After deploying the first smart contract, when I try to execute contract._constructor() an "Error: Execution Reverted" is triggered. It seems there is a problem when the contract interface object has a defined address. If the contract interface object has no address, it works.
So, make a `burrow.contract.deploy()` and then `contract._construct()` fails. But, make `burrow.contract.new()` and then `contract._construct()` works.

## Steps to Reproduce the Problem
 Solidity smart contract:
```
pragma solidity ^0.4.18;
contract SimpleContract {
  string thename;
  constructor(string newName) public {
    thename = newName;
  }
  function getName() public view returns (string name) {
    return thename;
  }
}
```

Javacript code using burrow.js:

```JavaScript
const monax = require('@monax/burrow');
const assert = require('assert');
var burrowURL = "localhost:10997";
var account = '7A634514CFD3210808F1E395B298489ECDD15F9B';
var options = { objectReturn: true };
var burrow = monax.createInstance(burrowURL, account, options);

// Get the contractABIJSON from somewhere such as solc
var abi = [{"constant":true,"inputs":[],"name":"getName","outputs":[{"name":"name","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"newName","type":"string"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"}]
var bytecode = "608060405234801561001057600080fd5b506040516102a83803806102a8833981018060405281019080805182019291905050508060009080519060200190610049929190610050565b50506100f5565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061009157805160ff19168380011785556100bf565b828001600101855582156100bf579182015b828111156100be5782518255916020019190600101906100a3565b5b5090506100cc91906100d0565b5090565b6100f291905b808211156100ee5760008160009055506001016100d6565b5090565b90565b6101a4806101046000396000f300608060405260043610610041576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806317d7de7c14610046575b600080fd5b34801561005257600080fd5b5061005b6100d6565b6040518080602001828103825283818151815260200191508051906020019080838360005b8381101561009b578082015181840152602081019050610080565b50505050905090810190601f1680156100c85780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b606060008054600181600116156101000203166002900480601f01602080910402602001604051908101604052809291908181526020018280546001816001161561010002031660029004801561016e5780601f106101435761010080835404028352916020019161016e565b820191906000526020600020905b81548152906001019060200180831161015157829003601f168201915b50505050509050905600a165627a7a72305820895940b85271a5e47f6139ebcda5a394cba8d33b21bd6a8abe6bee5873677b140029"


// I'm going to use deploy to create a first function followed by a direct call to the constructor to deploy a second contract

var contract;
let A2

burrow.contracts.deploy(abi, bytecode, 'contract1').then((ContractObject) => {
	contract = ContractObject;
	console.log(contract.address) // address of the first deployed contract
	return contract._constructor('contract2') // deploy a second contract
}).then((address)=>{
	A2 = address;
	console.log(A2)
	return Promise.all(
      [contract.getName(), 			// Note using the default address from the deploy
        contract.getName.at(A2)])   // Using the .at() to specify the second deployed contract
}).then(([result1, result2])=>{
	assert.equal(result1.values.name, "contract1")
	assert.equal(result2.values.name, "contract2")
})

```

Output:

> (node:18139) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
E16A43E1B2A5AE436F4ACA9B9CF784FB038E75EC
(node:18139) UnhandledPromiseRejectionWarning: Error: Execution Reverted
    at post (/home/mmartinez/datosunix/mikiproject/clientproject/node_modules/@monax/burrow/lib/contracts/function.js:134:21)
    at P.then (/home/mmartinez/datosunix/mikiproject/clientproject/node_modules/@monax/burrow/lib/service.js:64:37)
    at <anonymous>
(node:18139) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18139) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Thanks in advance

**Comment by helderjnpinto** [comment]
same issue ... thx

**Comment by dennismckinnon** [comment]
Thanks I'm looking into this now. Sorry for the delay in responding.
